fix(deps): update dependency org.springframework.boot:spring-boot-starter-parent to v2.7.14 (#754)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [org.springframework.boot:spring-boot-starter-parent](https://spring.io/projects/spring-boot) ([source](https://togithub.com/spring-projects/spring-boot)) | `2.7.13` -> `2.7.14` | [![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework.boot:spring-boot-starter-parent/2.7.14?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework.boot:spring-boot-starter-parent/2.7.14?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework.boot:spring-boot-starter-parent/2.7.13/2.7.14?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework.boot:spring-boot-starter-parent/2.7.13/2.7.14?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>spring-projects/spring-boot (org.springframework.boot:spring-boot-starter-parent)</summary>

### [`v2.7.14`](https://togithub.com/spring-projects/spring-boot/releases/tag/v2.7.14)

[Compare Source](https://togithub.com/spring-projects/spring-boot/compare/v2.7.13...v2.7.14)

#### :lady_beetle: Bug Fixes

-   Only one health group can be exposed using management.endpoint.health.group.xxx.additional-path=server:/newpath when using Jersey [#&#8203;36250](https://togithub.com/spring-projects/spring-boot/issues/36250)
-   MockitoPostProcessor doesn't check FactoryBean.OBJECT_TYPE_ATTRIBUTE correctly [#&#8203;36224](https://togithub.com/spring-projects/spring-boot/pull/36224)
-   ConfigurationPropertiesReportEndpoint does not display primitive wrapper types [#&#8203;36076](https://togithub.com/spring-projects/spring-boot/issues/36076)
-   When using Flyway 9.20.0, auto-configuration fails with a NoSuchMethodError due to the removal of Oracle-related methods from FluentConfiguration [#&#8203;36029](https://togithub.com/spring-projects/spring-boot/issues/36029)
-   Saml2RelyingPartyRegistrationConfiguration can choose the wrong RelyingPartyRegistration.Builder when using a metadata file with multiple providers [#&#8203;35902](https://togithub.com/spring-projects/spring-boot/pull/35902)
-   ImportsContextCustomizer does not support AliasFor [#&#8203;34917](https://togithub.com/spring-projects/spring-boot/pull/34917)
-   ConfigurationPropertyName#equals is not symmetric when element has trailing dashes [#&#8203;34804](https://togithub.com/spring-projects/spring-boot/pull/34804)

#### :notebook_with_decorative_cover: Documentation

-   Add Javadoc since to ImageReference.inTaglessForm() [#&#8203;36048](https://togithub.com/spring-projects/spring-boot/pull/36048)
-   Polish Kafka Properties Docs [#&#8203;36032](https://togithub.com/spring-projects/spring-boot/pull/36032)
-   Fix typo in the Using R2DBC section of the reference documentation [#&#8203;36019](https://togithub.com/spring-projects/spring-boot/pull/36019)
-   Improve Kubernetes liveness and readiness probes customization documentation [#&#8203;34978](https://togithub.com/spring-projects/spring-boot/pull/34978)
-   Document auto-configuration of underlying HTTP client when using WebClient or RestTemplate [#&#8203;34136](https://togithub.com/spring-projects/spring-boot/issues/34136)

#### :hammer: Dependency Upgrades

-   Upgrade to Elasticsearch 7.17.11 [#&#8203;36311](https://togithub.com/spring-projects/spring-boot/issues/36311)
-   Upgrade to Groovy 3.0.18 [#&#8203;36312](https://togithub.com/spring-projects/spring-boot/issues/36312)
-   Upgrade to Janino 3.1.10 [#&#8203;36313](https://togithub.com/spring-projects/spring-boot/issues/36313)
-   Upgrade to Johnzon 1.2.21 [#&#8203;36314](https://togithub.com/spring-projects/spring-boot/issues/36314)
-   Upgrade to Micrometer 1.9.13 [#&#8203;36171](https://togithub.com/spring-projects/spring-boot/issues/36171)
-   Upgrade to Neo4j Java Driver 4.4.12 [#&#8203;36315](https://togithub.com/spring-projects/spring-boot/issues/36315)
-   Upgrade to Rabbit AMQP Client 5.14.3 [#&#8203;36316](https://togithub.com/spring-projects/spring-boot/issues/36316)
-   Upgrade to Reactor Bom 2020.0.34 [#&#8203;36172](https://togithub.com/spring-projects/spring-boot/issues/36172)
-   Upgrade to Spring AMQP 2.4.14 [#&#8203;36399](https://togithub.com/spring-projects/spring-boot/issues/36399)
-   Upgrade to Spring Data Bom 2021.2.14 [#&#8203;36173](https://togithub.com/spring-projects/spring-boot/issues/36173)
-   Upgrade to Spring Framework 5.3.29 [#&#8203;36174](https://togithub.com/spring-projects/spring-boot/issues/36174)
-   Upgrade to Spring HATEOAS 1.5.5 [#&#8203;36413](https://togithub.com/spring-projects/spring-boot/issues/36413)
-   Upgrade to Spring Security 5.7.10 [#&#8203;36295](https://togithub.com/spring-projects/spring-boot/issues/36295)
-   Upgrade to Tomcat 9.0.78 [#&#8203;36317](https://togithub.com/spring-projects/spring-boot/issues/36317)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;ThomazPassarelli](https://togithub.com/ThomazPassarelli), [@&#8203;bbulgarelli](https://togithub.com/bbulgarelli), [@&#8203;bedla](https://togithub.com/bedla), [@&#8203;dependabot](https://togithub.com/dependabot)\[bot], [@&#8203;dkswnkk](https://togithub.com/dkswnkk), [@&#8203;eydunn](https://togithub.com/eydunn), [@&#8203;garyrussell](https://togithub.com/garyrussell), [@&#8203;izeye](https://togithub.com/izeye), [@&#8203;lasselindqvist](https://togithub.com/lasselindqvist), [@&#8203;lmartelli](https://togithub.com/lmartelli), and [@&#8203;quaff](https://togithub.com/quaff)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/GoogleCloudPlatform/kubernetes-engine-samples).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNi4xMS4wIiwidXBkYXRlZEluVmVyIjoiMzYuMTEuMCIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->