fix(deps): update dependency org.springframework.boot:spring-boot-starter-parent to v2.7.18 (#1045)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [org.springframework.boot:spring-boot-starter-parent](https://spring.io/projects/spring-boot) ([source](https://togithub.com/spring-projects/spring-boot)) | `2.7.17` -> `2.7.18` | [![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework.boot:spring-boot-starter-parent/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework.boot:spring-boot-starter-parent/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework.boot:spring-boot-starter-parent/2.7.17/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework.boot:spring-boot-starter-parent/2.7.17/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>spring-projects/spring-boot (org.springframework.boot:spring-boot-starter-parent)</summary>

### [`v2.7.18`](https://togithub.com/spring-projects/spring-boot/releases/tag/v2.7.18)

[Compare Source](https://togithub.com/spring-projects/spring-boot/compare/v2.7.17...v2.7.18)

#### ⚠️ Noteworthy Changes

-   Following the Paketo team's [announcement](https://blog.paketo.io/posts/paketo-bionic-builder-is-unsafe/) that the Bionic CNB builders will be removed, the default builder using by `bootBuildImage` (Gradle) and `spring-boot:build-image` (Maven) has been changed to Paketo Jammy [#&#8203;38477](https://togithub.com/spring-projects/spring-boot/issues/38477)

#### :lady_beetle: Bug Fixes

-   App fails to start with a NoSuchMethodError when using Flyway 10.0.0 [#&#8203;38164](https://togithub.com/spring-projects/spring-boot/issues/38164)
-   spring.webflux.multipart.max-disk-usage-per-part behaves incorrectly for values where the number of bytes overflows an int [#&#8203;38146](https://togithub.com/spring-projects/spring-boot/issues/38146)
-   Mail health indicator fails when host is not set in properties [#&#8203;38007](https://togithub.com/spring-projects/spring-boot/issues/38007)

#### :notebook_with_decorative_cover: Documentation

-   Document supported SQL comment prefixes [#&#8203;38385](https://togithub.com/spring-projects/spring-boot/pull/38385)
-   Fix link to Elasticsearch health indicator [#&#8203;38330](https://togithub.com/spring-projects/spring-boot/pull/38330)
-   Improve --help and documentation for "encodepassword -a/--algorithm" in the Spring Boot CLI [#&#8203;38203](https://togithub.com/spring-projects/spring-boot/issues/38203)
-   Document that TomcatConnectorCustomizers are not applied to additional connectors [#&#8203;38183](https://togithub.com/spring-projects/spring-boot/issues/38183)
-   MyErrorWebExceptionHandler example in documentation isn't working [#&#8203;38104](https://togithub.com/spring-projects/spring-boot/issues/38104)
-   Document that SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS is disabled by default [#&#8203;38083](https://togithub.com/spring-projects/spring-boot/issues/38083)
-   Update "Running Behind a Front-end Proxy Server" to include reactive and ForwardedHeaderTransformer [#&#8203;37282](https://togithub.com/spring-projects/spring-boot/issues/37282)
-   Improve documentation of `classpath.idx` file and its generation by the Maven and Gradle plugins [#&#8203;37125](https://togithub.com/spring-projects/spring-boot/issues/37125)
-   Document configuration for building images with Colima [#&#8203;34522](https://togithub.com/spring-projects/spring-boot/issues/34522)
-   Code sample in "Developing Your First Spring Boot Application" does not work [#&#8203;34513](https://togithub.com/spring-projects/spring-boot/issues/34513)
-   Document ConfigurationPropertyCaching [#&#8203;34172](https://togithub.com/spring-projects/spring-boot/issues/34172)
-   Document that application.\* banner variables require a packaged jar or the use of Boot's launcher [#&#8203;33489](https://togithub.com/spring-projects/spring-boot/issues/33489)
-   Add section on AspectJ support [#&#8203;32642](https://togithub.com/spring-projects/spring-boot/issues/32642)
-   Document server.servlet.encoding.\* properties and server.servlet.encoding.mapping in particular [#&#8203;32472](https://togithub.com/spring-projects/spring-boot/issues/32472)
-   Add a section on customizing embedded reactive servers [#&#8203;31917](https://togithub.com/spring-projects/spring-boot/issues/31917)
-   Clarify that MVC components provided through WebMvcRegistrations are subject to subsequent processing and configuration by MVC [#&#8203;31232](https://togithub.com/spring-projects/spring-boot/issues/31232)
-   Clarifying documentation on including a top-level `@TestConfiguration` class in a test [#&#8203;30513](https://togithub.com/spring-projects/spring-boot/issues/30513)
-   Clarify that `@AutoConfigureWebTestClient` binds WebTestClient to mock infrastructure [#&#8203;29890](https://togithub.com/spring-projects/spring-boot/issues/29890)
-   Improve systemd configuration documentation [#&#8203;28453](https://togithub.com/spring-projects/spring-boot/issues/28453)
-   Document how to customize the basePackages that auto-configurations consider (for example Spring Data Repositories) [#&#8203;27549](https://togithub.com/spring-projects/spring-boot/issues/27549)
-   Document additional user configuration that's required after setting `spring.hateoas.use-hal-as-default-json-media-type` to `false` [#&#8203;26814](https://togithub.com/spring-projects/spring-boot/issues/26814)
-   Add how-to documentation for test-only database migrations with Flyway/Liquibase [#&#8203;26796](https://togithub.com/spring-projects/spring-boot/issues/26796)

#### :hammer: Dependency Upgrades

-   Upgrade to ActiveMQ 5.16.7 [#&#8203;38427](https://togithub.com/spring-projects/spring-boot/issues/38427)
-   Upgrade to DB2 JDBC 11.5.9.0 [#&#8203;38428](https://togithub.com/spring-projects/spring-boot/issues/38428)
-   Upgrade to Dropwizard Metrics 4.2.22 [#&#8203;38429](https://togithub.com/spring-projects/spring-boot/issues/38429)
-   Upgrade to Elasticsearch 7.17.15 [#&#8203;38430](https://togithub.com/spring-projects/spring-boot/issues/38430)
-   Upgrade to Glassfish JAXB 2.3.9 [#&#8203;38431](https://togithub.com/spring-projects/spring-boot/issues/38431)
-   Upgrade to Micrometer 1.9.17 [#&#8203;38279](https://togithub.com/spring-projects/spring-boot/issues/38279)
-   Upgrade to Netty 4.1.101.Final [#&#8203;38432](https://togithub.com/spring-projects/spring-boot/issues/38432)
-   Upgrade to Pooled JMS 1.2.6 [#&#8203;38433](https://togithub.com/spring-projects/spring-boot/issues/38433)
-   Upgrade to Reactor Bom 2020.0.38 [#&#8203;38280](https://togithub.com/spring-projects/spring-boot/issues/38280)
-   Upgrade to Spring Batch 4.3.10 [#&#8203;38281](https://togithub.com/spring-projects/spring-boot/issues/38281)
-   Upgrade to Spring Data Bom 2021.2.18 [#&#8203;38282](https://togithub.com/spring-projects/spring-boot/issues/38282)
-   Upgrade to Spring Framework 5.3.31 [#&#8203;38283](https://togithub.com/spring-projects/spring-boot/issues/38283)
-   Upgrade to Spring HATEOAS 1.5.6 [#&#8203;38373](https://togithub.com/spring-projects/spring-boot/issues/38373)
-   Upgrade to Spring Integration 5.5.20 [#&#8203;38491](https://togithub.com/spring-projects/spring-boot/issues/38491)
-   Upgrade to Spring RESTDocs 2.0.8.RELEASE [#&#8203;38434](https://togithub.com/spring-projects/spring-boot/issues/38434)
-   Upgrade to Spring WS 3.1.8 [#&#8203;38284](https://togithub.com/spring-projects/spring-boot/issues/38284)
-   Upgrade to Tomcat 9.0.83 [#&#8203;38435](https://togithub.com/spring-projects/spring-boot/issues/38435)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;GVictorG7](https://togithub.com/GVictorG7), [@&#8203;PENEKhun](https://togithub.com/PENEKhun), [@&#8203;dreis2211](https://togithub.com/dreis2211), and [@&#8203;izeye](https://togithub.com/izeye)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on Monday" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/GoogleCloudPlatform/kubernetes-engine-samples).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy44MS4zIiwidXBkYXRlZEluVmVyIjoiMzcuODEuMyIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->